# -*- coding: utf-8 -*-
"""Text.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C6L8hCeuQ15XzGEr0HJD9AaIGd1gY4k4
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

#importing libraries
from keras.utils.vis_utils import plot_model
from keras.models import Model
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Input, Activation
from keras.layers import Flatten, BatchNormalization, Concatenate, add
from keras.layers import Embedding, Dropout, Conv1D, MaxPooling1D, Conv2D
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.layers.merge import concatenate
import tensorflow as tf
import os


#Loading the data in a dataframe
df = pd.read_csv('drive/My Drive/The_Research/all_data_refined.csv')
df = df.drop(['emotion'], axis = 1)
docs = df['text']

#test
for i in range(len(docs)):
  if docs[i] == "": print(i)

# prepare tokenizer
t = Tokenizer()
t.fit_on_texts(docs)
vocab_size = len(t.word_index) + 1

# integer encode the documents
encoded_docs = t.texts_to_sequences(docs)

# pad documents to a max length
wordlen = max(df['word_count'])
max_length = wordlen # Change this if needed
print("Max_Length: ", max_length)
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')


# load the whole embedding into memory
embeddings_index = dict()
f = open('drive/My Drive/glove_data/glove.6B/glove.6B.100d.txt')
for line in f:
	values = line.split()
	word = values[0]
	coefs = asarray(values[1:], dtype='float32')
	embeddings_index[word] = coefs
f.close()


# create a weight matrix for words in training docs
embedding_matrix = zeros((vocab_size, 100))
for word, i in t.word_index.items():
	embedding_vector = embeddings_index.get(word)
	if embedding_vector is not None:
		embedding_matrix[i] = embedding_vector


#load the labels
type = df['type']
labels = []
for types in type:
  if types == 'real':
    labels.append(1)
  elif types == 'fake':
    labels.append(0)


arr = df[df.columns[8: 23]]

listt = list()
for i in range(len(df)):
  listt.append(i)


X_train_1 = list()
X_train_2 = list()
X_test_1 = list()
X_test_2 = list()


X_train, X_test, y_train, y_test = train_test_split(listt, labels, test_size=0.33)

for i in X_train:
  X_train_1.append(padded_docs[i])
  X_train_2.append(arr.iloc[i])

for i in X_test:
  X_test_1.append(padded_docs[i])
  X_test_2.append(arr.iloc[i])


# define Implicit
inputs1 = Input(shape=(max_length,))
e = Embedding(vocab_size, 100, weights=[embedding_matrix], input_length=max_length, trainable=False)(inputs1)
a = (Dropout(0.5))(e)
b = (Conv1D(filters=10, kernel_size=(4)))(a)
c=MaxPooling1D(pool_size=2)(b)
d=Flatten()(c)
f=Dense(128)(d)
g=(BatchNormalization())(f)
z = Activation('relu')
h=(Dropout(0.8))(g)

# define Explicit
inputs2 = Input(shape=(15,))
q=(Dense(128))(inputs2)
r=(BatchNormalization())(q)
u=Activation('relu')(r)

print("h: ", h)
print("u: ", u)

merged = concatenate([h, u])
dense1 = Dense(10, activation='relu')(merged)
outputs = Dense(1, activation='sigmoid')(dense1)
model = Model(inputs=[inputs1, inputs2], outputs=outputs)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# summarize the model
print("____________________")
print(model.summary())
print("____________________")

plot_model(model, show_shapes=True, to_file='multichannelbeta.png')


# Saving the model:
checkpoint_path = "checkpoint.ckpt"
checkpoint_dir = os.path.dirname(checkpoint_path)

# Create a callback that saves the model's weights
cp_callback = tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_path,
                                                 save_weights_only=True,
                                                 verbose=1)

# fit the model
print("Fitting")
model.fit([X_train_1, X_train_2], array(y_train), epochs=5, verbose=1, batch_size=16)
print("Fitted")


model_json = model.to_json()
with open("textModel.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("textModel.h5")
print("Saved model to disk")


# evaluate the model
print("____________________")
loss, accuracy = model.evaluate([X_test_1, X_test_2] , array(y_test), verbose=1, batch_size=16)
print('Accuracy: %f' % (accuracy*100))

print("____________________")
output = model.predict([X_test_1, X_test_2])
print(output)


def finalOutputWithDelta(delta = 0.0):
  for i in range(len(output)):
    if output[i] >= (0.5 + delta):
      output[i] = 1
    elif output[i] < (0.5 + delta):
      output[i] = 0
  error = 0
  correct = 0
  for i in range(len(output)):
    error = error + ((output[i] - y_test[i]) ** 2)
    if output[i] == y_test[i]: correct+=1

  print("error: ", error)
  print(output)
  print(correct/6605)

# Loading the model:
from keras.models import Sequential
from keras.layers import Dense
from keras.models import model_from_json
import numpy
import os

# load json and create model
json_file = open('textModel.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("textModel.h5")
print("Loaded model from disk")

loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics= ['accuracy', 'mse'])
score = loaded_model.evaluate([X_test_1, X_test_2] , array(y_test), verbose=1)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

