# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18CGvKGBDLoZm007lz3ohHJ9T3lqvLotE
"""

from google.colab import drive
drive.mount('/content/drive')

test_df = pd.read_csv('drive/My Drive/The_Research/all_data_refined.csv', encoding='utf-8')
df = test_df
df.head()

fake_df = df[df['type']=='fake']
temp1 = fake_df.filter(['uuid', 'word_count'])
w_fake = list(temp1['word_count'])

real_df = df[df['type']=='real']
temp2 = real_df.filter(['uuid', 'word_count'])
w_real = list(temp2['word_count'])


plt.ylim(top = 2500)


# Create a figure instance
fig1 = plt.figure(1, figsize=(19, 16))

# Create an axes instance
ax1 = fig1.add_subplot(111)

# Create the boxplot
bp1 = ax1.boxplot(w_real)

# Save the figure
fig1.savefig('fig1.png', bbox_inches='tight')

