# -*- coding: utf-8 -*-
"""Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18CGvKGBDLoZm007lz3ohHJ9T3lqvLotE
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import matplotlib.pyplot as plt

test_df = pd.read_csv('drive/My Drive/The_Research/all_data_refined.csv', encoding='utf-8')
df = test_df
df.head(0)

import statistics as st

fake_df = df[df['type']=='fake']
temp1 = fake_df.filter(['uuid', 'word_count'])
w_fake = list(temp1['word_count'])

real_df = df[df['type']=='real']
temp2 = real_df.filter(['uuid', 'word_count'])
w_real = list(temp2['word_count'])


plt.bar(["Real", "Fake"], [st.mean(fake_df['capital_words']), st.mean(real_df['capital_words'])], color='green')
plt.xlabel("Type Of News")
plt.ylabel("Mean Capital Words Count")
plt.title("Statistics For Type Of News")
plt.savefig('Mean_capital_words_count.png', dpi = 400)
plt.show()

plt.bar(["Anger", "Disgust", "Fear", "Joy", "Sadness", "Surprise", "Trust", "Anticipation"], [emot_dict["Anger"],emot_dict["Disgust"],emot_dict["Fear"],emot_dict["Joy"],emot_dict["Sadness"],emot_dict["Surprise"],emot_dict["Trust"],emot_dict["Anticipation"]], color='blue')
plt.xlabel("Emotion")
plt.ylabel("Count")
plt.title("Emotion-Wise News Articles Count")
plt.savefig('Emotion_Distribution.png', dpi = 400)
plt.show()