# -*- coding: utf-8 -*-
"""Category_Analysis.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qucIi4mBsHDLfFn2NBBfdyHwwEq-WsEb
"""

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 1.14

#importing libraries
from keras.utils.vis_utils import plot_model
from keras.models import Model
from numpy import array
from numpy import asarray
from numpy import zeros
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Input, Activation
from keras.layers import Flatten, BatchNormalization, Concatenate, add
from keras.layers import Embedding, Dropout, Conv1D, MaxPooling1D, Conv2D
import pandas as pd
from sklearn.model_selection import train_test_split
from keras.layers.merge import concatenate



#Loading the data in a dataframe
df = pd.read_csv('drive/My Drive/The_Research/all_data_refined_v2.csv')
df['text'][3]

import statistics as st
import matplotlib.pyplot as plt

cat_dict = {'politics':0, 'tech':0, 'business':0, 'others':0, 'entertainment':0, 'sport':0}
cat_perc = {'politics':0, 'tech':0, 'business':0, 'others':0, 'entertainment':0, 'sport':0}

for i in range(len(df)):
  cat_dict[df['category'][i]] += 1

for cat in cat_perc:
  cat_perc[cat] = (cat_dict[cat] / 20015)*100

plt.bar(['politics', 'tech', 'business', 'others', 'entertainment', 'sport'],[cat_perc['politics'],cat_perc['tech'],cat_perc['business'],cat_perc['others'],cat_perc['entertainment'],cat_perc['sport']], color='green')
plt.xlabel("Category Of News")
plt.ylabel("Percent Of Articles")
plt.title("Statistics For Category Of News")
plt.savefig('Category_2.png', dpi = 400)
plt.show()

